Dataset Concat

In [ ]:
import pandas as pd 
Jan=pd.read_csv('january.csv',error_bad_lines=False,engine = 'python',header = None)
Feb=pd.read_csv('february.csv',error_bad_lines=False,engine = 'python',header = None)
Mar=pd.read_csv('march.csv',error_bad_lines=False,engine = 'python',header = None)
Apr=pd.read_csv('april.csv',error_bad_lines=False,engine = 'python',header = None)
May=pd.read_csv('may.csv',error_bad_lines=False,engine = 'python',header = None)
Jun=pd.read_csv('june.csv',error_bad_lines=False,engine = 'python',header = None)
Jul=pd.read_csv('july.csv',error_bad_lines=False,engine = 'python',header = None)
Aug=pd.read_csv('august.csv',error_bad_lines=False,engine = 'python',header = None)
Sep=pd.read_csv('september.csv',error_bad_lines=False,engine = 'python',header = None)
Oct=pd.read_csv('october.csv',error_bad_lines=False,engine = 'python',header = None)
Nov=pd.read_csv('november.csv',error_bad_lines=False,engine = 'python',header = None)
Final_2022=pd.concat([Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov])
Final_2022.to_csv('Sentiment2022.csv')

In [ ]:
df=pd.read_csv('Sentiment2022.csv',error_bad_lines=False,engine = 'python',header = None)
df.head(5)
#df_filtered = df.drop([0, 1])
df_filtered = df[df[2] != 'id']
df_filtered = df[df[13] == 'en']
df_filtered =df_filtered.drop([1,2,3,4,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37], axis=1)
df_filtered.head(5)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,0,5,6,12
3,2.0,2022-01-31,23:59:57,#Bitcoin is one of the most important inventi...
4,3.0,2022-01-31,23:59:52,"Lol... Oh, you just realized, you're still ear..."
5,4.0,2022-01-31,23:59:46,One of the largest asset managers on the plane...
7,6.0,2022-01-31,23:59:33,"However, if the report's claims are accurate, ..."
8,7.0,2022-01-31,23:59:33,The CoinShares report suggests that approximat...

In [ ]:
df_filtered.to_csv('Droped.csv')

In [ ]:
df=pd.read_csv('Droped.csv',error_bad_lines=False,engine = 'python',header = None)
df_filtered =df.drop([0,1],axis=1)

df_filtered.head(5)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

            2         3                                                  4
0           5         6                                                 12
1  2022-01-31  23:59:57  #Bitcoin  is one of the most important inventi...
2  2022-01-31  23:59:52  Lol... Oh, you just realized, you're still ear...
3  2022-01-31  23:59:46  One of the largest asset managers on the plane...
4  2022-01-31  23:59:33  However, if the report's claims are accurate, ...

In [ ]:
df_filtered.to_csv('Droped1.csv')

In [ ]:
df=pd.read_csv('Droped1.csv',error_bad_lines=False,engine = 'python',header = None)
# df.apply(pd.to_numeric, errors = 'coerce').dropna()
df = df.dropna()
df=df[df[3].apply(lambda x: len(x.split(' ')) > 3)]

df.to_csv('sentiment_preprocessed.csv')
df.head(5)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,0,1,2,3
2,1.0,2022-01-31,23:59:57,#Bitcoin is one of the most important inventi...
3,2.0,2022-01-31,23:59:52,"Lol... Oh, you just realized, you're still ear..."
4,3.0,2022-01-31,23:59:46,One of the largest asset managers on the plane...
5,4.0,2022-01-31,23:59:33,"However, if the report's claims are accurate, ..."
6,5.0,2022-01-31,23:59:33,The CoinShares report suggests that approximat...